version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: event-hub-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  redis:
    image: redis:8.4.0
    ports:
      - "6379:6379"
